# Generated by Django 4.2.2 on 2023-06-19 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_sku_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='sku_variant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='store.skuvariant'),
        ),
    ]
