# Generated by Django 4.2.2 on 2023-06-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_inventory_sku_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
