# Generated by Django 4.2.2 on 2023-06-20 11:57

from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_sku_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKUImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sku_images/')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=store.models.sku_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.sku')),
            ],
        ),
    ]
