# Generated by Django 4.2.2 on 2023-06-20 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_skuimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skuimage',
            old_name='profile_picture',
            new_name='sku_image',
        ),
        migrations.RemoveField(
            model_name='skuimage',
            name='image',
        ),
    ]
