# Generated by Django 4.2.2 on 2023-06-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_profile_picture_skuimage_sku_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skuimage',
            name='name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
