# Generated by Django 4.2.2 on 2023-06-20 19:30

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_skuimage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skuimage',
            name='sku_image',
            field=models.ImageField(default='store/static/store/assets/blank-image.jpg', upload_to=store.models.sku_directory_path),
        ),
    ]
