# Generated by Django 4.2.2 on 2023-06-22 15:35

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_skuimage_sku_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skuimage',
            name='sku_image',
            field=models.ImageField(default='static/store/assets/blank-image.jpg ', upload_to=store.models.sku_directory_path),
        ),
    ]
