# Generated by Django 4.2.2 on 2023-06-25 22:56

import django.core.validators
from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_skuimage_sku_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skuimage',
            name='sku_image',
            field=models.ImageField(default='sku_images/default/blank-image.jpg', upload_to=store.models.sku_directory_path),
        ),
        migrations.AlterField(
            model_name='skureview',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
